//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kkd_specopg_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class arrangementer
    {
        public int id { get; set; }
        public System.DateTime fra_dato { get; set; }
        public int varighed { get; set; }
        public int antal_deltagere { get; set; }
        public int fk_kunde { get; set; }
        public int fk_hotel { get; set; }
        public int fk_moedelokale { get; set; }
    
        public virtual hoteller hoteller { get; set; }
        public virtual kunder kunder { get; set; }
        public virtual moedelokaler moedelokaler { get; set; }
    }
}
