//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kkd_specopg_ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_hotelkaedeEntities : DbContext
    {
        public db_hotelkaedeEntities()
            : base("name=db_hotelkaedeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arrangementer> arrangementer { get; set; }
        public virtual DbSet<hoteller> hoteller { get; set; }
        public virtual DbSet<kunder> kunder { get; set; }
        public virtual DbSet<ledigevaerelser> ledigevaerelser { get; set; }
        public virtual DbSet<moedelokaler> moedelokaler { get; set; }
        public virtual DbSet<priser> priser { get; set; }
    
        public virtual int proc_udskriv_pris(Nullable<int> booking_id)
        {
            var booking_idParameter = booking_id.HasValue ?
                new ObjectParameter("booking_id", booking_id) :
                new ObjectParameter("booking_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_udskriv_pris", booking_idParameter);
        }
    }
}
