//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kkd_specopg_LINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class moedelokaler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public moedelokaler()
        {
            this.arrangementer = new HashSet<arrangementer>();
        }
    
        public int id { get; set; }
        public int nummer { get; set; }
        public int kapacitet { get; set; }
        public int fk_hotel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arrangementer> arrangementer { get; set; }
        public virtual hoteller hoteller { get; set; }
    }
}
